Finish lesson 2 exercises
arbatskiy/thinknetica-ruby-exercises pull request #2
Opened 2016-11-10 08:32 UTC by arbatskiy

2016-11-10 10:52 UTC, psylone requested changes

2016-11-10 10:52 UTC, psylone commented on 2_Ruby_Basics/2_array_1_100.rb
> +for num in (10..100)
Посмотри как это можно сделать с помощью метода итератора.

2016-11-10 10:52 UTC, psylone commented on 2_Ruby_Basics/4_array_vowels.rb
> +vowels = letters.select { |key, value| key.to_s.match(/[aouie]/) }
Можно уменьшить количество итераций если итерировать по гласным вместо алфавита.

2016-11-10 10:52 UTC, psylone commented on 2_Ruby_Basics/5_date_number.rb
> +puts "Error! Day can be only 1-31" if day < 1 || day > 31
Такие условия удобно записывать так: `puts 'Super duper error message' unless (1..31) === day`.

2016-11-10 10:52 UTC, psylone commented on 2_Ruby_Basics/5_date_number.rb
> +leap = year % 4 == 0 && year % 100 != 0
Такую логику читать немного не комфортно. Попробуй все условия определить в рамках **одного** выражения.

2016-11-10 10:52 UTC, psylone commented on 2_Ruby_Basics/5_date_number.rb
> +for num in (1...month) do
Проверь дату `12 февраля 2000 года`.

2016-11-10 10:52 UTC, psylone commented on 2_Ruby_Basics/6_shopping_card.rb
> +    shopping_card[name.to_sym] = { price => quantity }
Что если пользователь введёт товар название которого уже существует но с другим количеством и ценой?

2016-11-10 10:52 UTC, psylone commented
Благодарю за пулл реквест, так намного удобней! )

2016-11-11 10:19 UTC, arbatskiy commented on 2_Ruby_Basics/5_date_number.rb
> +for num in (1...month) do
43й день, вроде все норм? или я не так понял задание?

2016-11-11 11:15 UTC, arbatskiy commented on 2_Ruby_Basics/4_array_vowels.rb
> +vowels = letters.select { |key, value| key.to_s.match(/[aouie]/) }
Тут что то не могу понять, как итерировать по гласным, все равно ведь нужно все перебрать, чтобы выбрать гласные. Или ('a'..'u'), вместо z?)

2016-11-11 16:23 UTC, psylone commented on 2_Ruby_Basics/4_array_vowels.rb
> +vowels = letters.select { |key, value| key.to_s.match(/[aouie]/) }
Можно обходить гласные и с помощью метода для массива вычислять индекс этой гласной в алфавите.

2016-11-11 16:27 UTC, psylone commented on 2_Ruby_Basics/5_date_number.rb
> +for num in (1...month) do
Всё в порядке, не досмотрел.

2016-11-12 08:45 UTC, merged